# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ble.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'ble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tble.proto\x1a\x0c\x63ommon.proto\"5\n\x10\x62le_data_message\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x11\n\tmember_id\x18\x02 \x01(\t\"\xc3\x01\n\x07\x62le_msg\x12\x46\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:\x1b\x65num_SERVICE_TYPE_INDEX_BLE\x12G\n\x10\x62le_operate_type\x18\x02 \x02(\x0e\x32\x11.BLE_OPERATE_TYPE:\x1a\x65num_BLE_OPERATE_TYPE_NONE\x12\'\n\x0c\x62le_data_msg\x18\x03 \x03(\x0b\x32\x11.ble_data_message*\xc7\x01\n\x10\x42LE_OPERATE_TYPE\x12\x1e\n\x1a\x65num_BLE_OPERATE_TYPE_NONE\x10\x00\x12#\n\x1f\x65num_BLE_OPERATE_TYPE_BOND_INFO\x10\x01\x12\"\n\x1e\x65num_BLE_OPERATE_TYPE_BOND_REQ\x10\x02\x12(\n$enum_BLE_OPERATE_TYPE_CONNECT_STATUS\x10\x03\x12 \n\x1c\x65num_BLE_OPERATE_TYPE_UNBOND\x10\x04\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_BLE_OPERATE_TYPE']._serialized_start=281
  _globals['_BLE_OPERATE_TYPE']._serialized_end=480
  _globals['_BLE_DATA_MESSAGE']._serialized_start=27
  _globals['_BLE_DATA_MESSAGE']._serialized_end=80
  _globals['_BLE_MSG']._serialized_start=83
  _globals['_BLE_MSG']._serialized_end=278
# @@protoc_insertion_point(module_scope)
