# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"~\n\x15\x66ile_list_get_message\x12\x10\n\x08\x66ile_num\x18\x01 \x01(\r\x12!\n\x19\x66ile_list_support_num_max\x18\x02 \x01(\r\x12\x18\n\x10\x66ile_index_start\x18\x03 \x01(\r\x12\x16\n\x0e\x66ile_index_end\x18\x04 \x01(\r*\x9a\x07\n\x12service_type_index\x12 \n\x1c\x65num_SERVICE_TYPE_INDEX_NONE\x10\x00\x12\x1f\n\x1b\x65num_SERVICE_TYPE_INDEX_INS\x10\x01\x12\x1f\n\x1b\x65num_SERVICE_TYPE_INDEX_MAP\x10\x02\x12 \n\x1c\x65num_SERVICE_TYPE_INDEX_BACK\x10\x03\x12$\n enum_SERVICE_TYPE_INDEX_FIRMWARE\x10\x04\x12 \n\x1c\x65num_SERVICE_TYPE_INDEX_WIFI\x10\x05\x12(\n$enum_SERVICE_TYPE_INDEX_CYCLING_DATA\x10\x06\x12&\n\"enum_SERVICE_TYPE_INDEX_ROUTE_PLAN\x10\x07\x12+\n\'enum_SERVICE_TYPE_INDEX_REAL_TIME_TRACE\x10\x08\x12\'\n#enum_SERVICE_TYPE_INDEX_USER_CONFIG\x10\t\x12\x1f\n\x1b\x65num_SERVICE_TYPE_INDEX_BLE\x10\n\x12#\n\x1f\x65num_SERVICE_TYPE_INDEX_FACTORY\x10\x0b\x12\"\n\x1e\x65num_SERVICE_TYPE_INDEX_CONFIG\x10\x0c\x12&\n\"enum_SERVICE_TYPE_INDEX_DEV_STATUS\x10\r\x12\"\n\x1e\x65num_SERVICE_TYPE_INDEX_SENSOR\x10\x0e\x12$\n enum_SERVICE_TYPE_INDEX_TRAINING\x10\x0f\x12%\n!enum_SERVICE_TYPE_INDEX_TEAM_INFO\x10\x10\x12(\n$enum_SERVICE_TYPE_INDEX_DEV_VER_INFO\x10\x11\x12$\n enum_SERVICE_TYPE_INDEX_LANGUAGE\x10\x12\x12\x1f\n\x1b\x65num_SERVICE_TYPE_INDEX_LOG\x10\x13\x12!\n\x1d\x65num_SERVICE_TYPE_INDEX_THEME\x10\x14\x12*\n&enum_SERVICE_TYPE_INDEX_FILE_OPERATION\x10\x15\x12#\n\x1f\x65num_SERVICE_TYPE_INDEX_MAP_NEW\x10\x16\x12&\n\"enum_SERVICE_TYPE_INDEX_ROUTE_BOOK\x10\x17*\xc6\x01\n\x14SERVICE_OPERATE_TYPE\x12\"\n\x1e\x65num_SERVICE_OPERATE_TYPE_NONE\x10\x00\x12!\n\x1d\x65num_SERVICE_OPERATE_TYPE_SET\x10\x01\x12!\n\x1d\x65num_SERVICE_OPERATE_TYPE_GET\x10\x02\x12!\n\x1d\x65num_SERVICE_OPERATE_TYPE_ADD\x10\x03\x12!\n\x1d\x65num_SERVICE_OPERATE_TYPE_DEL\x10\x04\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_SERVICE_TYPE_INDEX']._serialized_start=145
  _globals['_SERVICE_TYPE_INDEX']._serialized_end=1067
  _globals['_SERVICE_OPERATE_TYPE']._serialized_start=1070
  _globals['_SERVICE_OPERATE_TYPE']._serialized_end=1268
  _globals['_FILE_LIST_GET_MESSAGE']._serialized_start=16
  _globals['_FILE_LIST_GET_MESSAGE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
