# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cycling_data.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'cycling_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ycling_data.proto\x1a\x0c\x63ommon.proto\"j\n\x1e\x63ycling_data_file_flag_message\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\x11\n\tfile_size\x18\x02 \x01(\r\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\tdevice_id\x18\x04 \x01(\t\"l\n cycling_data_auto_upload_message\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x18\n\x10\x63ycling_data_url\x18\x02 \x01(\t\x12\x1e\n\x16\x63ycling_data_check_url\x18\x03 \x01(\t\"\x95\x03\n\x10\x63ycling_data_msg\x12O\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:$enum_SERVICE_TYPE_INDEX_CYCLING_DATA\x12\x62\n\x19\x63ycling_data_operate_type\x18\x02 \x02(\x0e\x32\x1a.CYCLING_DATA_OPERATE_TYPE:#enum_CYCLING_DATA_OPERATE_TYPE_NONE\x12\x43\n\x1a\x63ycling_data_file_flag_msg\x18\x03 \x03(\x0b\x32\x1f.cycling_data_file_flag_message\x12\x14\n\x0c\x66ile_content\x18\x04 \x01(\x0c\x12G\n\x1c\x63ycling_data_auto_upload_msg\x18\x05 \x01(\x0b\x32!.cycling_data_auto_upload_message\x12(\n\x08list_msg\x18\x06 \x01(\x0b\x32\x16.file_list_get_message*\xb4\x03\n\x19\x43YCLING_DATA_OPERATE_TYPE\x12\'\n#enum_CYCLING_DATA_OPERATE_TYPE_NONE\x10\x00\x12+\n\'enum_CYCLING_DATA_OPERATE_TYPE_LIST_GET\x10\x01\x12,\n(enum_CYCLING_DATA_OPERATE_TYPE_LIST_SEND\x10\x02\x12+\n\'enum_CYCLING_DATA_OPERATE_TYPE_FILE_GET\x10\x03\x12,\n(enum_CYCLING_DATA_OPERATE_TYPE_FILE_SEND\x10\x04\x12+\n\'enum_CYCLING_DATA_OPERATE_TYPE_FILE_DEL\x10\x05\x12*\n&enum_CYCLING_DATA_OPERATE_TYPE_ALL_DEL\x10\x06\x12.\n*enum_CYCLING_DATA_OPERATE_TYPE_AUTO_UPLOAD\x10\x07\x12/\n+enum_CYCLING_DATA_OPERATE_TYPE_LIST_NUM_GET\x10\x08\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cycling_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_CYCLING_DATA_OPERATE_TYPE']._serialized_start=663
  _globals['_CYCLING_DATA_OPERATE_TYPE']._serialized_end=1099
  _globals['_CYCLING_DATA_FILE_FLAG_MESSAGE']._serialized_start=36
  _globals['_CYCLING_DATA_FILE_FLAG_MESSAGE']._serialized_end=142
  _globals['_CYCLING_DATA_AUTO_UPLOAD_MESSAGE']._serialized_start=144
  _globals['_CYCLING_DATA_AUTO_UPLOAD_MESSAGE']._serialized_end=252
  _globals['_CYCLING_DATA_MSG']._serialized_start=255
  _globals['_CYCLING_DATA_MSG']._serialized_end=660
# @@protoc_insertion_point(module_scope)
