# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_ver_info.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'dev_ver_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65v_ver_info.proto\x1a\x0c\x63ommon.proto\"\xac\x01\n\x0bversion_msg\x12\x15\n\rmain_boot_ver\x18\x01 \x01(\r\x12\x14\n\x0cmain_app_ver\x18\x02 \x01(\r\x12\x14\n\x0c\x62le_boot_ver\x18\x03 \x01(\r\x12\x13\n\x0b\x62le_app_ver\x18\x04 \x01(\r\x12\x14\n\x0chardware_ver\x18\x05 \x01(\r\x12\x19\n\x0cprotocol_ver\x18\x06 \x01(\r:\x03\x31\x30\x31\x12\x14\n\x0c\x63ompile_time\x18\x07 \x01(\t\"\xc7\x01\n\x10\x64\x65v_ver_info_msg\x12O\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:$enum_SERVICE_TYPE_INDEX_DEV_VER_INFO\x12;\n\x0coperate_type\x18\x02 \x02(\x0e\x32\r.OPERATE_TYPE:\x16\x65num_OPERATE_TYPE_NONE\x12%\n\x0fversion_message\x18\x03 \x01(\x0b\x32\x0c.version_msg*\xb2\x01\n\x0cOPERATE_TYPE\x12\x1a\n\x16\x65num_OPERATE_TYPE_NONE\x10\x00\x12\x19\n\x15\x65num_OPERATE_TYPE_SET\x10\x01\x12\x19\n\x15\x65num_OPERATE_TYPE_GET\x10\x02\x12\x1a\n\x16\x65num_OPERATE_TYPE_SEND\x10\x03\x12\x19\n\x15\x65num_OPERATE_TYPE_ADD\x10\x04\x12\x19\n\x15\x65num_OPERATE_TYPE_DEL\x10\x05\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_ver_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_OPERATE_TYPE']._serialized_start=414
  _globals['_OPERATE_TYPE']._serialized_end=592
  _globals['_VERSION_MSG']._serialized_start=37
  _globals['_VERSION_MSG']._serialized_end=209
  _globals['_DEV_VER_INFO_MSG']._serialized_start=212
  _globals['_DEV_VER_INFO_MSG']._serialized_end=411
# @@protoc_insertion_point(module_scope)
