# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_download.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'file_download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_download.proto\"Y\n\rfile_download\x12\x11\n\tfile_size\x18\x01 \x02(\r\x12\x11\n\tfile_type\x18\x02 \x01(\r\x12\x0f\n\x07\x66ile_id\x18\x03 \x01(\r\x12\x11\n\tfile_name\x18\x04 \x01(\tB\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_FILE_DOWNLOAD']._serialized_start=23
  _globals['_FILE_DOWNLOAD']._serialized_end=112
# @@protoc_insertion_point(module_scope)
