# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: firmware.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'firmware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66irmware.proto\x1a\x0c\x63ommon.proto\"\x9f\x01\n\x15\x66irmware_data_message\x12\x18\n\x10mcu_firmware_ver\x18\x01 \x01(\r\x12\x18\n\x10\x62le_firmware_ver\x18\x02 \x01(\r\x12\x15\n\rfirmware_size\x18\x03 \x01(\r\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0f\n\x07process\x18\x05 \x01(\r\x12\x1d\n\x15\x62le_boot_firmware_ver\x18\x06 \x01(\r\"\xe6\x01\n\x0c\x66irmware_msg\x12K\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index: enum_SERVICE_TYPE_INDEX_FIRMWARE\x12V\n\x15\x66irmware_operate_type\x18\x02 \x02(\x0e\x32\x16.FIRMWARE_OPERATE_TYPE:\x1f\x65num_FIRMWARE_OPERATE_TYPE_NONE\x12\x31\n\x11\x66irmware_data_msg\x18\x03 \x01(\x0b\x32\x16.firmware_data_message*\x94\x02\n\x15\x46IRMWARE_OPERATE_TYPE\x12#\n\x1f\x65num_FIRMWARE_OPERATE_TYPE_NONE\x10\x00\x12*\n&enum_FIRMWARE_OPERATE_TYPE_GET_VERSION\x10\x01\x12+\n\'enum_FIRMWARE_OPERATE_TYPE_SEND_VERSION\x10\x02\x12)\n%enum_FIRMWARE_OPERATE_TYPE_MCU_UPDATE\x10\x03\x12\'\n#enum_FIRMWARE_OPERATE_TYPE_PROGRESS\x10\x04\x12)\n%enum_FIRMWARE_OPERATE_TYPE_BLE_UPDATE\x10\x05\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'firmware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_FIRMWARE_OPERATE_TYPE']._serialized_start=428
  _globals['_FIRMWARE_OPERATE_TYPE']._serialized_end=704
  _globals['_FIRMWARE_DATA_MESSAGE']._serialized_start=33
  _globals['_FIRMWARE_DATA_MESSAGE']._serialized_end=192
  _globals['_FIRMWARE_MSG']._serialized_start=195
  _globals['_FIRMWARE_MSG']._serialized_end=425
# @@protoc_insertion_point(module_scope)
