# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: general_file_operation.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'general_file_operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgeneral_file_operation.proto\x1a\x0c\x63ommon.proto\"\xc2\x02\n\x16general_file_operation\x12Q\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:&enum_SERVICE_TYPE_INDEX_FILE_OPERATION\x12K\n\x0coperate_type\x18\x02 \x02(\x0e\x32\x15.SERVICE_OPERATE_TYPE:\x1e\x65num_SERVICE_OPERATE_TYPE_NONE\x12\'\n\tfile_type\x18\x03 \x02(\x0e\x32\x14.file_operation_type\x12\x11\n\tfile_size\x18\x04 \x02(\r\x12\x0f\n\x07\x66ile_id\x18\x05 \x02(\r\x12\x11\n\tfile_name\x18\x06 \x01(\t\x12\x16\n\x0e\x66ile_extension\x18\x07 \x01(\t\x12\x10\n\x08\x66ile_md5\x18\x08 \x01(\t*\x91\x02\n\x13\x66ile_operation_type\x12\x1a\n\x16\x65num_FILE_TYPE_GENERAL\x10\x00\x12\x1b\n\x17\x65num_FILE_TYPE_TRAINING\x10\x01\x12\x1d\n\x19\x65num_FILE_TYPE_ROUTE_PLAN\x10\x02\x12\x16\n\x12\x65num_FILE_TYPE_MAP\x10\x03\x12\x18\n\x14\x65num_FILE_TYPE_THEME\x10\x04\x12\x1b\n\x17\x65num_FILE_TYPE_FIRMWARE\x10\x05\x12\x1b\n\x17\x65num_FILE_TYPE_LANGUAGE\x10\x06\x12\x17\n\x13\x65num_FILE_TYPE_AGPS\x10\x07\x12\x1d\n\x19\x65num_FILE_TYPE_ROUTE_BOOK\x10\x08\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'general_file_operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_FILE_OPERATION_TYPE']._serialized_start=372
  _globals['_FILE_OPERATION_TYPE']._serialized_end=645
  _globals['_GENERAL_FILE_OPERATION']._serialized_start=47
  _globals['_GENERAL_FILE_OPERATION']._serialized_end=369
# @@protoc_insertion_point(module_scope)
