# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: language_pack.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'language_pack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import config_pb2 as config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13language_pack.proto\x1a\x0c\x63ommon.proto\x1a\x0c\x63onfig.proto\"\x80\x01\n\x1dlanguage_pack_module_info_msg\x12\x34\n\x0bsupport_cmd\x18\x01 \x03(\x0e\x32\x1f.LANGUAGE_PACK_SUB_OPERATE_TYPE\x12)\n\x1clanguage_pack_module_version\x18\x02 \x01(\r:\x03\x31\x30\x30\"\xe6\x01\n\x16language_pack_info_msg\x12\x41\n\rlanguage_type\x18\x01 \x02(\x0e\x32\x0e.LANGUAGE_TYPE:\x1a\x65num_LANGUAGE_TYPE_INVALID\x12\x17\n\x0flanguage_versin\x18\x02 \x01(\r\x12+\n\tfont_type\x18\x03 \x01(\x0e\x32\x18.LANGUAGE_PACK_FONT_TYPE\x12\x11\n\tfont_size\x18\x04 \x01(\r\x12\x11\n\tpack_size\x18\x05 \x01(\r\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x10\n\x08md5_code\x18\x07 \x01(\x0c\"\xa1\x03\n\x11language_pack_msg\x12K\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index: enum_SERVICE_TYPE_INDEX_LANGUAGE\x12K\n\x0coperate_type\x18\x02 \x02(\x0e\x32\x15.SERVICE_OPERATE_TYPE:\x1e\x65num_SERVICE_OPERATE_TYPE_NONE\x12\x61\n\x14language_sub_operate\x18\x03 \x02(\x0e\x32\x1f.LANGUAGE_PACK_SUB_OPERATE_TYPE:\"enum_LANG_SUB_OPERATE_TYPE_INVALID\x12;\n\x1alanguage_pack_info_message\x18\x04 \x03(\x0b\x32\x17.language_pack_info_msg\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\x12;\n\x13module_info_message\x18\x10 \x01(\x0b\x32\x1e.language_pack_module_info_msgJ\x04\x08\x06\x10\x10*\xa4\x02\n\x1eLANGUAGE_PACK_SUB_OPERATE_TYPE\x12&\n\"enum_LANG_SUB_OPERATE_TYPE_INVALID\x10\x00\x12/\n+enum_LANG_SUB_OPERATE_TYPE_SET_DOWNLOAD_URL\x10\x01\x12.\n*enum_LANG_SUB_OPERATE_TYPE_GET_MODULE_INFO\x10\x10\x12\'\n#enum_LANG_SUB_OPERATE_TYPE_GET_LIST\x10\x11\x12\'\n#enum_LANG_SUB_OPERATE_TYPE_ADD_PACK\x10 \x12\'\n#enum_LANG_SUB_OPERATE_TYPE_DEL_PACK\x10\x30*V\n\x17LANGUAGE_PACK_FONT_TYPE\x12(\n$enum_LANGUAGE_PACK_FONT_TYPE_INVALID\x10\x00\x12\x11\n\renum_DianDian\x10\x01\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'language_pack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_LANGUAGE_PACK_SUB_OPERATE_TYPE']._serialized_start=836
  _globals['_LANGUAGE_PACK_SUB_OPERATE_TYPE']._serialized_end=1128
  _globals['_LANGUAGE_PACK_FONT_TYPE']._serialized_start=1130
  _globals['_LANGUAGE_PACK_FONT_TYPE']._serialized_end=1216
  _globals['_LANGUAGE_PACK_MODULE_INFO_MSG']._serialized_start=52
  _globals['_LANGUAGE_PACK_MODULE_INFO_MSG']._serialized_end=180
  _globals['_LANGUAGE_PACK_INFO_MSG']._serialized_start=183
  _globals['_LANGUAGE_PACK_INFO_MSG']._serialized_end=413
  _globals['_LANGUAGE_PACK_MSG']._serialized_start=416
  _globals['_LANGUAGE_PACK_MSG']._serialized_end=833
# @@protoc_insertion_point(module_scope)
