# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x1a\x0c\x63ommon.proto\"\x86\x02\n\x07log_msg\x12\x41\n\x07service\x18\x01 \x02(\x0e\x32\x13.service_type_index:\x1b\x65num_SERVICE_TYPE_INDEX_LOG\x12\x46\n\x07operate\x18\x02 \x02(\x0e\x32\x15.SERVICE_OPERATE_TYPE:\x1e\x65num_SERVICE_OPERATE_TYPE_NONE\x12<\n\x0bsub_operate\x18\x03 \x02(\x0e\x32\x15.LOG_SUB_OPERATE_TYPE:\x10\x65num_LOG_INVALID\x12\x10\n\x08log_name\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\x12\x0f\n\x07log_num\x18\x06 \x01(\r*W\n\x14LOG_SUB_OPERATE_TYPE\x12\x14\n\x10\x65num_LOG_INVALID\x10\x00\x12\x17\n\x13\x65num_LOG_NUMBER_GET\x10\x10\x12\x10\n\x0c\x65num_LOG_GET\x10\x11\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_LOG_SUB_OPERATE_TYPE']._serialized_start=292
  _globals['_LOG_SUB_OPERATE_TYPE']._serialized_end=379
  _globals['_LOG_MSG']._serialized_start=28
  _globals['_LOG_MSG']._serialized_end=290
# @@protoc_insertion_point(module_scope)
