# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map_new.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'map_new.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmap_new.proto\x1a\x0c\x63ommon.proto\"U\n\x10map_list_message\x12\x18\n\x10map_country_name\x18\x01 \x01(\t\x12\x0e\n\x06map_id\x18\x02 \x01(\r\x12\x17\n\x0fmap_coordinates\x18\x03 \x01(\t\"\x8a\x02\n\x0bmap_new_msg\x12J\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:\x1f\x65num_SERVICE_TYPE_INDEX_MAP_NEW\x12\x31\n\x0bmap_op_type\x18\x02 \x02(\x0e\x32\x0c.map_op_type:\x0eMAP_OP_INVALID\x12\'\n\x0cmap_list_msg\x18\x03 \x03(\x0b\x32\x11.map_list_message\x12!\n\nmap_op_sta\x18\x04 \x01(\x0e\x32\r.map_op_state\x12\x30\n\x10map_list_get_msg\x18\x05 \x01(\x0b\x32\x16.file_list_get_message*\x9a\x01\n\x0bmap_op_type\x12\x12\n\x0eMAP_OP_INVALID\x10\x00\x12\x17\n\x13MAP_OP_LIST_NUM_GET\x10\x01\x12\x13\n\x0fMAP_OP_LIST_GET\x10\x02\x12\x13\n\x0fMAP_OP_DOWNLOAD\x10\x03\x12\x11\n\rMAP_OP_UPDATE\x10\x04\x12\x11\n\rMAP_OP_DELETE\x10\x05\x12\x0e\n\nMAP_OP_SET\x10\x06*V\n\x0cmap_op_state\x12\x18\n\x14MAP_OP_STATE_INVALID\x10\x00\x12\x16\n\x12MAP_OP_STATE_START\x10\x01\x12\x14\n\x10MAP_OP_STATE_END\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_new_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAP_OP_TYPE']._serialized_start=388
  _globals['_MAP_OP_TYPE']._serialized_end=542
  _globals['_MAP_OP_STATE']._serialized_start=544
  _globals['_MAP_OP_STATE']._serialized_end=630
  _globals['_MAP_LIST_MESSAGE']._serialized_start=31
  _globals['_MAP_LIST_MESSAGE']._serialized_end=116
  _globals['_MAP_NEW_MSG']._serialized_start=119
  _globals['_MAP_NEW_MSG']._serialized_end=385
# @@protoc_insertion_point(module_scope)
