# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x1a\x0c\x63ommon.proto\"\x94\x01\n\x10map_data_message\x12\x0e\n\x06map_id\x18\x01 \x01(\r\x12\x0f\n\x07\x61rea_id\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\x11\n\tarea_type\x18\x06 \x01(\r\x12\x10\n\x08progress\x18\x07 \x01(\r\x12\x0e\n\x06\x63onfig\x18\x08 \x01(\r\"\xc3\x01\n\x07map_msg\x12\x46\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:\x1b\x65num_SERVICE_TYPE_INDEX_MAP\x12G\n\x10map_operate_type\x18\x02 \x02(\x0e\x32\x11.MAP_OPERATE_TYPE:\x1a\x65num_MAP_OPERATE_TYPE_NONE\x12\'\n\x0cmap_data_msg\x18\x03 \x03(\x0b\x32\x11.map_data_message*\xf1\x03\n\x10MAP_OPERATE_TYPE\x12\x1e\n\x1a\x65num_MAP_OPERATE_TYPE_NONE\x10\x00\x12\"\n\x1e\x65num_MAP_OPERATE_TYPE_LIST_GET\x10\x01\x12#\n\x1f\x65num_MAP_OPERATE_TYPE_LIST_SEND\x10\x02\x12\'\n#enum_MAP_OPERATE_TYPE_ASSIGN_UPDATE\x10\x03\x12$\n enum_MAP_OPERATE_TYPE_ALL_UPDATE\x10\x04\x12\"\n\x1e\x65num_MAP_OPERATE_TYPE_DOWNLOAD\x10\x05\x12!\n\x1d\x65num_MAP_OPERATE_TYPE_SUCCESS\x10\x06\x12)\n%enum_MAP_OPERATE_YPTE_CANCEL_DOWNLOAD\x10\x07\x12&\n\"enum_MAP_OPERATE_TYPE_PROGRESS_GET\x10\x08\x12)\n%enum_MAP_OPERATE_TYPE_PROGRESS_UPLOAD\x10\t\x12$\n enum_MAP_OPERATE_TYPE_ASSIGN_DEL\x10\n\x12!\n\x1d\x65num_MAP_OPERATE_TYPE_ALL_DEL\x10\x0b\x12\x17\n\x13\x65num_MAP_CONFIG_CMD\x10\x0c\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_MAP_OPERATE_TYPE']._serialized_start=377
  _globals['_MAP_OPERATE_TYPE']._serialized_end=874
  _globals['_MAP_DATA_MESSAGE']._serialized_start=28
  _globals['_MAP_DATA_MESSAGE']._serialized_end=176
  _globals['_MAP_MSG']._serialized_start=179
  _globals['_MAP_MSG']._serialized_end=374
# @@protoc_insertion_point(module_scope)
