from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PERIPHERAL_SERVICE_TYPE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PST_UNSPECIFIED: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_INFO: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_CONFIG: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_HR: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_RADAR: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_FIRMWARE: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_FACTORY: _ClassVar[PERIPHERAL_SERVICE_TYPE]
    PST_OEM: _ClassVar[PERIPHERAL_SERVICE_TYPE]

class PERIPHERAL_OPERATE_TYPE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    POT_UNSPECIFIED: _ClassVar[PERIPHERAL_OPERATE_TYPE]
    POT_SET: _ClassVar[PERIPHERAL_OPERATE_TYPE]
    POT_GET: _ClassVar[PERIPHERAL_OPERATE_TYPE]
    POT_ADD: _ClassVar[PERIPHERAL_OPERATE_TYPE]
    POT_DEL: _ClassVar[PERIPHERAL_OPERATE_TYPE]
PST_UNSPECIFIED: PERIPHERAL_SERVICE_TYPE
PST_INFO: PERIPHERAL_SERVICE_TYPE
PST_CONFIG: PERIPHERAL_SERVICE_TYPE
PST_HR: PERIPHERAL_SERVICE_TYPE
PST_RADAR: PERIPHERAL_SERVICE_TYPE
PST_FIRMWARE: PERIPHERAL_SERVICE_TYPE
PST_FACTORY: PERIPHERAL_SERVICE_TYPE
PST_OEM: PERIPHERAL_SERVICE_TYPE
POT_UNSPECIFIED: PERIPHERAL_OPERATE_TYPE
POT_SET: PERIPHERAL_OPERATE_TYPE
POT_GET: PERIPHERAL_OPERATE_TYPE
POT_ADD: PERIPHERAL_OPERATE_TYPE
POT_DEL: PERIPHERAL_OPERATE_TYPE
