# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peripheral_firmware.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'peripheral_firmware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import peripheral_common_pb2 as peripheral__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19peripheral_firmware.proto\x1a\x17peripheral_common.proto\"U\n\x1bperipheral_firmware_message\x12\x17\n\x0f\x62in_packet_size\x18\x06 \x01(\r\x12\x17\n\x0f\x62in_packet_data\x18\x07 \x01(\x0cJ\x04\x08\x01\x10\x06\"\x9b\x02\n\x1aperipheral_firmware_format\x12.\n\x0cservice_type\x18\x01 \x01(\x0e\x32\x18.PERIPHERAL_SERVICE_TYPE\x12.\n\x0coperate_type\x18\x02 \x01(\x0e\x32\x18.PERIPHERAL_OPERATE_TYPE\x12\x36\n\x10sub_service_type\x18\x03 \x01(\x0e\x32\x1c.PERIPHERAL_FIRMWARE_SERVICE\x12\x36\n\x10sub_operate_type\x18\x04 \x01(\x0e\x32\x1c.PERIPHERAL_FIRMWARE_OPERATE\x12-\n\x07message\x18\x05 \x01(\x0b\x32\x1c.peripheral_firmware_message*Y\n\x1bPERIPHERAL_FIRMWARE_SERVICE\x12\x13\n\x0fPFS_UNSPECIFIED\x10\x00\x12\x11\n\rPFS_ENTER_DFU\x10\x01\x12\x12\n\x0ePFS_MCU_UPDATE\x10\x02*\x9a\x01\n\x1bPERIPHERAL_FIRMWARE_OPERATE\x12\x13\n\x0fPFO_UNSPECIFIED\x10\x00\x12\x18\n\x14PFO_MCU_UPDATE_START\x10\x01\x12\x1a\n\x16PFO_MCU_UPDATE_PROCESS\x10\x02\x12\x16\n\x12PFO_MCU_UPDATE_END\x10\x03\x12\x18\n\x14PFO_MCU_UPDATE_ERROR\x10\x04\x42\x1c\n\x18\x63om.igpsport.blelib.beanH\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peripheral_firmware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.beanH\001'
  _globals['_PERIPHERAL_FIRMWARE_SERVICE']._serialized_start=427
  _globals['_PERIPHERAL_FIRMWARE_SERVICE']._serialized_end=516
  _globals['_PERIPHERAL_FIRMWARE_OPERATE']._serialized_start=519
  _globals['_PERIPHERAL_FIRMWARE_OPERATE']._serialized_end=673
  _globals['_PERIPHERAL_FIRMWARE_MESSAGE']._serialized_start=54
  _globals['_PERIPHERAL_FIRMWARE_MESSAGE']._serialized_end=139
  _globals['_PERIPHERAL_FIRMWARE_FORMAT']._serialized_start=142
  _globals['_PERIPHERAL_FIRMWARE_FORMAT']._serialized_end=425
# @@protoc_insertion_point(module_scope)
