# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peripheral_radar.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'peripheral_radar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import peripheral_common_pb2 as peripheral__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16peripheral_radar.proto\x1a\x17peripheral_common.proto\"T\n\x1fperipheral_radar_target_message\x12\r\n\x05level\x18\x06 \x01(\x05\x12\r\n\x05range\x18\x07 \x01(\x05\x12\r\n\x05speed\x18\x08 \x01(\x05J\x04\x08\x01\x10\x06\"?\n\x16peripheral_acc_message\x12\t\n\x01x\x18\x06 \x01(\x05\x12\t\n\x01y\x18\x07 \x01(\x05\x12\t\n\x01z\x18\x08 \x01(\x05J\x04\x08\x01\x10\x06\"\x81\x01\n\x18peripheral_radar_message\x12\x34\n\nradar_info\x18\x06 \x03(\x0b\x32 .peripheral_radar_target_message\x12)\n\x08\x61\x63\x63_info\x18\x07 \x03(\x0b\x32\x17.peripheral_acc_messageJ\x04\x08\x01\x10\x06\"\x8f\x02\n\x17peripheral_radar_format\x12.\n\x0cservice_type\x18\x01 \x01(\x0e\x32\x18.PERIPHERAL_SERVICE_TYPE\x12.\n\x0coperate_type\x18\x02 \x01(\x0e\x32\x18.PERIPHERAL_OPERATE_TYPE\x12\x33\n\x10sub_service_type\x18\x03 \x01(\x0e\x32\x19.PERIPHERAL_RADAR_SERVICE\x12\x33\n\x10sub_operate_type\x18\x04 \x01(\x0e\x32\x19.PERIPHERAL_RADAR_OPERATE\x12*\n\x07meaagse\x18\x05 \x01(\x0b\x32\x19.peripheral_radar_message*4\n\x18PERIPHERAL_RADAR_SERVICE\x12\x18\n\x14PHS_NSPECIFIED_RADAR\x10\x00*^\n\x18PERIPHERAL_RADAR_OPERATE\x12\x18\n\x14PHO_NSPECIFIED_RADAR\x10\x00\x12\x14\n\x10PHO_RADAR_TARGET\x10\x01\x12\x12\n\x0ePHO_ACC_SAMPLE\x10\x02\x42\x1c\n\x18\x63om.igpsport.blelib.beanH\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peripheral_radar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.beanH\001'
  _globals['_PERIPHERAL_RADAR_SERVICE']._serialized_start=608
  _globals['_PERIPHERAL_RADAR_SERVICE']._serialized_end=660
  _globals['_PERIPHERAL_RADAR_OPERATE']._serialized_start=662
  _globals['_PERIPHERAL_RADAR_OPERATE']._serialized_end=756
  _globals['_PERIPHERAL_RADAR_TARGET_MESSAGE']._serialized_start=51
  _globals['_PERIPHERAL_RADAR_TARGET_MESSAGE']._serialized_end=135
  _globals['_PERIPHERAL_ACC_MESSAGE']._serialized_start=137
  _globals['_PERIPHERAL_ACC_MESSAGE']._serialized_end=200
  _globals['_PERIPHERAL_RADAR_MESSAGE']._serialized_start=203
  _globals['_PERIPHERAL_RADAR_MESSAGE']._serialized_end=332
  _globals['_PERIPHERAL_RADAR_FORMAT']._serialized_start=335
  _globals['_PERIPHERAL_RADAR_FORMAT']._serialized_end=606
# @@protoc_insertion_point(module_scope)
