# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peripheral_oem.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'peripheral_oem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import peripheral_common_pb2 as peripheral__common__pb2
from . import peripheral_info_pb2 as peripheral__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14peripheral_oem.proto\x1a\x17peripheral_common.proto\x1a\x15peripheral_info.proto\"\'\n\x17peripheral_oem_data_ble\x12\x0c\n\x04name\x18\x01 \x01(\t\"b\n\x1aperipheral_oem_data_device\x12*\n\x05model\x18\x01 \x01(\x0e\x32\x1b.PERIPHERAL_INFO_MODEL_TYPE\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\"<\n peripheral_oem_data_manufacturer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\"\xb4\x01\n\x16peripheral_oem_message\x12*\n\x08\x62le_info\x18\x01 \x01(\x0b\x32\x18.peripheral_oem_data_ble\x12\x30\n\x0b\x64\x65vice_info\x18\x02 \x01(\x0b\x32\x1b.peripheral_oem_data_device\x12<\n\x11manufacturer_info\x18\x03 \x01(\x0b\x32!.peripheral_oem_data_manufacturer\"\x87\x02\n\x15peripheral_oem_format\x12.\n\x0cservice_type\x18\x01 \x01(\x0e\x32\x18.PERIPHERAL_SERVICE_TYPE\x12.\n\x0coperate_type\x18\x02 \x01(\x0e\x32\x18.PERIPHERAL_OPERATE_TYPE\x12\x31\n\x10sub_service_type\x18\x03 \x01(\x0e\x32\x17.PERIPHERAL_OEM_SERVICE\x12\x31\n\x10sub_operate_type\x18\x04 \x01(\x0e\x32\x17.PERIPHERAL_OEM_OPERATE\x12(\n\x07message\x18\x05 \x01(\x0b\x32\x17.peripheral_oem_message*\x86\x01\n\x16PERIPHERAL_OEM_SERVICE\x12\x13\n\x0fPOS_UNSPECIFIED\x10\x00\x12\x10\n\x0cPOS_BLE_INFO\x10\x01\x12\x13\n\x0fPOS_DEVICE_INFO\x10\x02\x12\x19\n\x15POS_MANUFACTURER_INFO\x10\x03\x12\x0f\n\x0bPOS_ALL_OEM\x10\x0b\"\x04\x08\x04\x10\n*-\n\x16PERIPHERAL_OEM_OPERATE\x12\x13\n\x0fPOO_UNSPECIFIED\x10\x00\x42\x1c\n\x18\x63om.igpsport.blelib.beanH\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peripheral_oem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.beanH\001'
  _globals['_PERIPHERAL_OEM_SERVICE']._serialized_start=725
  _globals['_PERIPHERAL_OEM_SERVICE']._serialized_end=859
  _globals['_PERIPHERAL_OEM_OPERATE']._serialized_start=861
  _globals['_PERIPHERAL_OEM_OPERATE']._serialized_end=906
  _globals['_PERIPHERAL_OEM_DATA_BLE']._serialized_start=72
  _globals['_PERIPHERAL_OEM_DATA_BLE']._serialized_end=111
  _globals['_PERIPHERAL_OEM_DATA_DEVICE']._serialized_start=113
  _globals['_PERIPHERAL_OEM_DATA_DEVICE']._serialized_end=211
  _globals['_PERIPHERAL_OEM_DATA_MANUFACTURER']._serialized_start=213
  _globals['_PERIPHERAL_OEM_DATA_MANUFACTURER']._serialized_end=273
  _globals['_PERIPHERAL_OEM_MESSAGE']._serialized_start=276
  _globals['_PERIPHERAL_OEM_MESSAGE']._serialized_end=456
  _globals['_PERIPHERAL_OEM_FORMAT']._serialized_start=459
  _globals['_PERIPHERAL_OEM_FORMAT']._serialized_end=722
# @@protoc_insertion_point(module_scope)
