# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peripheral_common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'peripheral_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17peripheral_common.proto*\xac\x01\n\x17PERIPHERAL_SERVICE_TYPE\x12\x13\n\x0fPST_UNSPECIFIED\x10\x00\x12\x0c\n\x08PST_INFO\x10\x65\x12\x0e\n\nPST_CONFIG\x10\x66\x12\n\n\x06PST_HR\x10g\x12\r\n\tPST_RADAR\x10h\x12\x10\n\x0cPST_FIRMWARE\x10y\x12\x10\n\x0bPST_FACTORY\x10\x83\x01\x12\x0c\n\x07PST_OEM\x10\x84\x01\"\x04\x08\x01\x10\x64\"\x04\x08i\x10x\"\x05\x08z\x10\x82\x01*b\n\x17PERIPHERAL_OPERATE_TYPE\x12\x13\n\x0fPOT_UNSPECIFIED\x10\x00\x12\x0b\n\x07POT_SET\x10\x01\x12\x0b\n\x07POT_GET\x10\x02\x12\x0b\n\x07POT_ADD\x10\x03\x12\x0b\n\x07POT_DEL\x10\x04\x42\x1c\n\x18\x63om.igpsport.blelib.beanH\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peripheral_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.beanH\001'
  _globals['_PERIPHERAL_SERVICE_TYPE']._serialized_start=28
  _globals['_PERIPHERAL_SERVICE_TYPE']._serialized_end=200
  _globals['_PERIPHERAL_OPERATE_TYPE']._serialized_start=202
  _globals['_PERIPHERAL_OPERATE_TYPE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
