# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: real_time_trace.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'real_time_trace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15real_time_trace.proto\x1a\x0c\x63ommon.proto\"E\n\x1breal_time_trace_fit_message\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\x13\n\x0b\x66it_content\x18\x02 \x01(\x0c\"\x95\x02\n\x13real_time_trace_msg\x12R\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:\'enum_SERVICE_TYPE_INDEX_REAL_TIME_TRACE\x12k\n\x1creal_time_trace_operate_type\x18\x02 \x02(\x0e\x32\x1d.REAL_TIME_TRACE_OPERATE_TYPE:&enum_REAL_TIME_TRACE_OPERATE_TYPE_NONE\x12=\n\x17real_time_trace_fit_msg\x18\x03 \x01(\x0b\x32\x1c.real_time_trace_fit_message*\xf9\x01\n\x1cREAL_TIME_TRACE_OPERATE_TYPE\x12*\n&enum_REAL_TIME_TRACE_OPERATE_TYPE_NONE\x10\x00\x12)\n%enum_REAL_TIME_TRACE_OPERATE_TYPE_GET\x10\x01\x12)\n%enum_REAL_TIME_TRACE_OPERATE_TYPE_FIT\x10\x02\x12,\n(enum_REAL_TIME_TRACE_OPERATE_TYPE_FINISH\x10\x03\x12)\n%enum_REAL_TIME_TRACE_OPERATE_TYPE_END\x10\x04\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'real_time_trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_REAL_TIME_TRACE_OPERATE_TYPE']._serialized_start=391
  _globals['_REAL_TIME_TRACE_OPERATE_TYPE']._serialized_end=640
  _globals['_REAL_TIME_TRACE_FIT_MESSAGE']._serialized_start=39
  _globals['_REAL_TIME_TRACE_FIT_MESSAGE']._serialized_end=108
  _globals['_REAL_TIME_TRACE_MSG']._serialized_start=111
  _globals['_REAL_TIME_TRACE_MSG']._serialized_end=388
# @@protoc_insertion_point(module_scope)
