# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: route_book.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'route_book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10route_book.proto\x1a\x0c\x63ommon.proto\"]\n\x18route_book_infor_message\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\'\n\x06status\x18\x07 \x01(\x0e\x32\x17.ROUTE_BOOK_FILE_STATUS\"\x82\x03\n\x13route_book_data_msg\x12M\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:\"enum_SERVICE_TYPE_INDEX_ROUTE_BOOK\x12K\n\x0coperate_type\x18\x02 \x02(\x0e\x32\x15.SERVICE_OPERATE_TYPE:\x1e\x65num_SERVICE_OPERATE_TYPE_NONE\x12W\n\x10sub_operate_type\x18\x03 \x02(\x0e\x32\x17.ROUTE_BOOK_SUB_OP_TYPE:$enum_ROUTE_BOOK_GET_SUB_OP_TYPE_NONE\x12\x37\n\x14route_book_infor_msg\x18\x04 \x03(\x0b\x32\x19.route_book_infor_message\x12\x37\n\x17route_book_list_get_msg\x18\n \x01(\x0b\x32\x16.file_list_get_messageJ\x04\x08\x05\x10\n*\xf7\x01\n\x16ROUTE_BOOK_SUB_OP_TYPE\x12(\n$enum_ROUTE_BOOK_GET_SUB_OP_TYPE_NONE\x10\x00\x12\x30\n,enum_ROUTE_BOOK_GET_SUB_OP_TYPE_LIST_NUM_GET\x10\x01\x12,\n(enum_ROUTE_BOOK_GET_SUB_OP_TYPE_LIST_GET\x10\x02\x12\'\n#enum_ROUTE_BOOK_SET_SUB_OP_TYPE_USE\x10\x11\x12*\n&enum_ROUTE_BOOK_SET_SUB_OP_TYPE_RENAME\x10\x12*\x8f\x01\n\x16ROUTE_BOOK_FILE_STATUS\x12\'\n#enum_ROUTE_BOOK_FILE_INVALID_STATUS\x10\x00\x12$\n enum_ROUTE_BOOK_FILE_USED_STATUS\x10\x01\x12&\n\"enum_ROUTE_BOOK_FILE_UNUSED_STATUS\x10\x02\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_ROUTE_BOOK_SUB_OP_TYPE']._serialized_start=519
  _globals['_ROUTE_BOOK_SUB_OP_TYPE']._serialized_end=766
  _globals['_ROUTE_BOOK_FILE_STATUS']._serialized_start=769
  _globals['_ROUTE_BOOK_FILE_STATUS']._serialized_end=912
  _globals['_ROUTE_BOOK_INFOR_MESSAGE']._serialized_start=34
  _globals['_ROUTE_BOOK_INFOR_MESSAGE']._serialized_end=127
  _globals['_ROUTE_BOOK_DATA_MSG']._serialized_start=130
  _globals['_ROUTE_BOOK_DATA_MSG']._serialized_end=516
# @@protoc_insertion_point(module_scope)
