# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: team_info.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'team_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fteam_info.proto\x1a\x0c\x63ommon.proto\"l\n\x12team_info_data_msg\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x0e\n\x06status\x18\x03 \x01(\r\x12\x11\n\tnick_name\x18\x04 \x01(\t\x12\x0e\n\x06\x63ourse\x18\x05 \x01(\x05\"\x81\x02\n\rteam_info_msg\x12L\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:!enum_SERVICE_TYPE_INDEX_TEAM_INFO\x12Y\n\x16team_info_operate_type\x18\x02 \x02(\x0e\x32\x17.TEAM_INFO_OPERATE_TYPE: enum_TEAM_INFO_OPERATE_TYPE_NONE\x12\x12\n\nmember_num\x18\x03 \x01(\r\x12\x33\n\x16team_info_data_message\x18\x04 \x03(\x0b\x32\x13.team_info_data_msg*c\n\x16TEAM_INFO_OPERATE_TYPE\x12$\n enum_TEAM_INFO_OPERATE_TYPE_NONE\x10\x00\x12#\n\x1f\x65num_TEAM_INFO_OPERATE_TYPE_SET\x10\x01*\xe5\x01\n\x11MEMBER_STATE_TYPE\x12\"\n\x1e\x65num_MEMBER_STATE_TYPE_INVALID\x10\x00\x12!\n\x1d\x65num_MEMBER_STATE_TYPE_NORMAL\x10\x01\x12#\n\x1f\x65num_MEMBER_STATE_TYPE_ABNORMAL\x10\x02\x12\"\n\x1e\x65num_MEMBER_STATE_TYPE_OFFLINE\x10\x03\x12\x1f\n\x1b\x65num_MEMBER_STATE_TYPE_JOIN\x10\x04\x12\x1f\n\x1b\x65num_MEMBER_STATE_TYPE_QUIT\x10\x05\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'team_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_TEAM_INFO_OPERATE_TYPE']._serialized_start=403
  _globals['_TEAM_INFO_OPERATE_TYPE']._serialized_end=502
  _globals['_MEMBER_STATE_TYPE']._serialized_start=505
  _globals['_MEMBER_STATE_TYPE']._serialized_end=734
  _globals['_TEAM_INFO_DATA_MSG']._serialized_start=33
  _globals['_TEAM_INFO_DATA_MSG']._serialized_end=141
  _globals['_TEAM_INFO_MSG']._serialized_start=144
  _globals['_TEAM_INFO_MSG']._serialized_end=401
# @@protoc_insertion_point(module_scope)
