# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_config.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'user_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11user_config.proto\x1a\x0c\x63ommon.proto\"\x9e\x01\n\x14user_config_data_msg\x12\x0b\n\x03sex\x18\x01 \x01(\r\x12\x0e\n\x06weight\x18\x02 \x01(\r\x12\x0b\n\x03\x61ge\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x11\n\twheel_dia\x18\x05 \x01(\r\x12\x13\n\x0b\x62ike_weight\x18\x06 \x01(\r\x12\x11\n\ttime_zone\x18\x07 \x01(\x05\x12\x11\n\tmember_id\x18\x08 \x01(\t\"\xfb\x01\n\x0fuser_config_msg\x12N\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:#enum_SERVICE_TYPE_INDEX_USER_CONFIG\x12_\n\x18user_config_operate_type\x18\x02 \x02(\x0e\x32\x19.USER_CONFIG_OPERATE_TYPE:\"enum_USER_CONFIG_OPERATE_TYPE_NONE\x12\x37\n\x18user_config_data_message\x18\x03 \x01(\x0b\x32\x15.user_config_data_msg*\x90\x01\n\x18USER_CONFIG_OPERATE_TYPE\x12&\n\"enum_USER_CONFIG_OPERATE_TYPE_NONE\x10\x00\x12%\n!enum_USER_CONFIG_OPERATE_TYPE_SET\x10\x01\x12%\n!enum_USER_CONFIG_OPERATE_TYPE_GET\x10\x02\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_USER_CONFIG_OPERATE_TYPE']._serialized_start=451
  _globals['_USER_CONFIG_OPERATE_TYPE']._serialized_end=595
  _globals['_USER_CONFIG_DATA_MSG']._serialized_start=36
  _globals['_USER_CONFIG_DATA_MSG']._serialized_end=194
  _globals['_USER_CONFIG_MSG']._serialized_start=197
  _globals['_USER_CONFIG_MSG']._serialized_end=448
# @@protoc_insertion_point(module_scope)
