# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wifi.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'wifi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwifi.proto\x1a\x0c\x63ommon.proto\"l\n\x11wifi_data_message\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0c\n\x04ssid\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x13\n\x0bopen_status\x18\x04 \x01(\r\x12\x17\n\x0fsignal_strength\x18\x05 \x01(\r\"\xca\x01\n\x08wifi_msg\x12G\n\x0cservice_type\x18\x01 \x02(\x0e\x32\x13.service_type_index:\x1c\x65num_SERVICE_TYPE_INDEX_WIFI\x12J\n\x11wifi_operate_type\x18\x02 \x02(\x0e\x32\x12.WIFI_OPERATE_TYPE:\x1b\x65num_WIFI_OPERATE_TYPE_NONE\x12)\n\rwifi_data_msg\x18\x03 \x03(\x0b\x32\x12.wifi_data_message*\xf0\x02\n\x11WIFI_OPERATE_TYPE\x12\x1f\n\x1b\x65num_WIFI_OPERATE_TYPE_NONE\x10\x00\x12%\n!enum_WIFI_OPERATE_TYPE_STATUS_GET\x10\x01\x12&\n\"enum_WIFI_OPERATE_TYPE_STATUS_SEND\x10\x02\x12\x1f\n\x1b\x65num_WIFI_OPERATE_TYPE_CTRL\x10\x03\x12#\n\x1f\x65num_WIFI_OPERATE_TYPE_LIST_GET\x10\x04\x12$\n enum_WIFI_OPERATE_TYPE_LIST_SEND\x10\x05\x12&\n\"enum_WIFI_OPERATE_TYPE_ASSIGN_SSID\x10\x06\x12*\n&enum_WIFI_OPERATE_TYPE_AUTO_STATUS_GET\x10\x07\x12+\n\'enum_WIFI_OPERATE_TYPE_AUTO_STATUS_SEND\x10\x08\x42\x1a\n\x18\x63om.igpsport.blelib.bean')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wifi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.igpsport.blelib.bean'
  _globals['_WIFI_OPERATE_TYPE']._serialized_start=344
  _globals['_WIFI_OPERATE_TYPE']._serialized_end=712
  _globals['_WIFI_DATA_MESSAGE']._serialized_start=28
  _globals['_WIFI_DATA_MESSAGE']._serialized_end=136
  _globals['_WIFI_MSG']._serialized_start=139
  _globals['_WIFI_MSG']._serialized_end=341
# @@protoc_insertion_point(module_scope)
